#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

#Create a dummy file to open the case in Paraview
caseName=$(basename $(dirname $(readlink -f "$0")))
touch ${caseName}.foam

runApplication blockMesh
#runApplication -s 1 topoSet -dict system/topoSetDict1
#runApplication -s 1 refineMesh -dict system/refineMeshDict1 -overwrite

runApplication setAlphaField

runApplication $(getApplication)

#------------------------------------------------------------------------------
